title: Jonas Halvorsen, PhD
#email: example@example.org
description: >- # this means to ignore newlines until "baseurl:"
  Academic webpage for Jonas Halvorsen, PhD.
  
#theme: jekyll-theme-minimal
#markdown: kramdown
#remote_theme: "mmistakes/minimal-mistakes@4.16.4"

plugins:
  - jekyll-relative-links
  - jekyll-include-cache
relative_links:
  enabled: true
  collections: true
