#theme: jekyll-theme-minimal
theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-relative-links
  - jekyll-include-cache
relative_links:
  enabled: true
  collections: true
include:
  - README.md
