#theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes@4.16.4"

plugins:
  - jekyll-relative-links
  - jekyll-include-cache
relative_links:
  enabled: true
  collections: true
include:
  - README.md
